name: LobbySystem
version: ${project.version}
main: de.nehlen.lobbysystem.LobbySystem
api-version: 1.13
depend: [MCCommons,GameAPI]
authors: [DasNiklas]
commands:
  build:
    aliases:
      - bau
      - edit
  setspawn:
    aliases:
      - set
