name: LobbySystem
version: ${project.version}
main: de.zayon.lobbysystem.LobbySystem
api-version: 1.13
depend: [MCCommons]
authors: [DasNiklas]
commands:
  build:
    aliases:
      - bau
      - edit
  setspawn:
    aliases:
      - set
